name: Hello

on:
  push:
    - main

jobs:
    greet: 
       runs-on: ubuntu-latest
       steps: 
         - name: Checkout Code
           run : actions/checkout@v4
         - name: Says Hello to user
           run : echo "Hello from Github Actions!"
           
