name: Hello

on:
  push:
    branches:
      - main

jobs:
    greet: 
       runs-on: ubuntu-latest
       steps: 
         - name: Checkout Code
           uses : actions/checkout@v4
         
         - name: Says Hello to user
           run : echo "Hello from Github Actions!"

         - name: Print branch name
           run : echo "The branch name is ${{github.ref_name}}"

         - name: Print Current Date
           run : echo "date"

         - name: Print list of file
           run : echo "ls"

         - name: Print the current OS
           run : echo "cat /etc/os-release"
           
