name: Reusable Build Workflow

on:
  workflow_call:
    inputs:
      app_name:
        description: "Name of the Application"
        required: true
        type: string

      environment:
        description: "Deployment environment"
        required: true
        default: staging
        type: string

    secrets: 
      docker_token:
        description: "Docker Hub Token"
        required: true
   
    outputs:
      build_version:
        description: "Generate Build Version"
        value: ${{ jobs.build.output.build_version }}
          
          
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Build Information
        run: |
          echo "Building ${{ inputs.app_name }} for ${{ inputs.environment }}"

      - name: Verfiy Docker Token
        run: |
          echo "Docker token is set: ${{ secrets.docker_token != '' }}"

      - name: Generate Build Version
        id: version
        run: |
          VERSION="v1.0-${GITHUB_SHA::7}"
          echo "Generated version $VERSION"
          echo "build_version=$VERSION" >> "$GITHUB_OUTPUT"
